server:
  port: ${PORT}

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: TRANSFERT-SERVICE
          uri: lb://TRANSFERT-SERVICE
          predicates:
            - Path=/transferts/**
          filters:
            - name: CircuitBreaker
              args:
                name: TRANSFERT-SERVICE
                fallbackuri: forward:/transfertServiceFallBack
        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/clients/**
          filters:
            - name: CircuitBreaker
              args:
                name: CLIENT-SERVICE
                fallbackuri: forward:/clientsServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : https://service-registry-application.herokuapp.com/eureka/
  instance:
    hostname: cloud-gateway-application.herokuapp.com
    homePageUrl: http://${eureka.instance.hostname}/
    secure-port-enabled: true
    non-secure-port-enabled: false
    non-secure-port: 80
    securePort: 443




